# CONFIGURACIÓN DE CONEXIÓN A POSTGRESQL
spring.datasource.url=jdbc:postgresql://localhost:5432/carritos
spring.datasource.username=postgres
spring.datasource.password=Los;petetes;2026

# CONFIGURACIÓN DE JPA HIBERNATE
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
# update: Crea las tablas automáticamente si no existen sin borrar tus datos previos
spring.jpa.hibernate.ddl-auto=update
# Muestra en la consola de IntelliJ las consultas SQL reales que se están ejecutando
spring.jpa.show-sql=true
